use 8657capgemini;
create table dept(deptid varchar(60),deptname varchar(60),city varchar(55),state varchar(60));
desc dept;
insert into dept(deptid,deptname,city,state)values('A002','EEE','Mumbai','Maharashtra');
select * from dept;
alter table dept modify column deptid varchar(56) not null;
desc dept;
insert into dept(deptname,city,state)values('DBA','Delhi','New Delhi');
insert into dept(deptid,deptname,city,state)values('A003','Admin','Pune','Maharashtra');
alter table dept modify column deptid varchar(56) default 'A000';
insert into dept(deptname,city,state)values('DBA','Delhi','New Delhi');
alter table dept modify column deptid varchar(67) primary key;
alter table dept modify column deptname varchar(67) unique;
delete from dept where deptid='A003';
select * from cust;
alter table cust add constraint check(age<23);
create table empdetails(eid int,ename varchar(78),salary int,check(salary>100000));
insert into empdetails(eid,ename,salary)values(101,'shivani',120000);
alter table empdetails add check(salary>=12000);
select * from empdetails;
create index empindex on empdetails(eid);
show index from empdetails;