use practice;
create table emp(id int,name varchar(30),address varchar(30),phono int);
desc emp;
insert into emp values(101,'shivani','thakurki',9975865);
select * from emp;
insert into emp(id,name,address,phono)values(102,'samu','phaltan',1234),(103,'deepali','mol',5678);
update emp set name='dipali'where id=103;
alter table emp add column age int;
update emp set age=21 where id=101;
update emp set age=15 where id=102;
update emp set age=35 where id=103;
select * from emp where id=101;
select * from emp where name like '%s';
select * from emp where name like 's%';
select * from emp where name like '__i%';
select * from emp where name like '%s%';
select * from emp where age between 15 and 27;
select * from emp where age in(15,21,38);
alter table emp add column(salary1 double,salary2 double,ctc double);
insert into emp(salary1,salary2)values(12000,34000);
update emp set salary1=12300,salary2=23000 where id=101;
alter table emp add column ctc double;
desc emp;
update emp set ctc=salary1+salary2 where id=101;
select * from emp;